export enum SubType {
  EXPENSE = 'EXPENSE',
  SAVING = 'SAVING',
  EDUCATION = 'EDUCATION',
  ENJOYMENT = 'ENJOYMENT',
  INVESTMENT = 'INVESTMENT',
  DONATION = 'DONATION',
  SALARY = 'SALARY',
  SUB_JOB = 'SUB_JOB',
  PARENT = 'PARENT',
  UN_INVESTMENT = 'UN_INVESTMENT',
  LOTERY = 'LOTERY',
}

export enum Type {
  SPENDING = 'SPENDING',
  INCOME = 'INCOME',
}

export enum Currency {
  DOLLAR = 'DOLLAR',
  VND = 'VND',
}
