export enum AuthEnum {
  PUBLIC = 'PUBLIC',
  WITH_ACTIVE_TOKEN_ONLY = 'WITH_ACTIVE_TOKEN_ONLY',
  WITH_EXPIRED_TOKEN_ONLY = 'WITH_EXPIRED_TOKEN_ONLY',
  WITHOUT_TOKEN_ONLY = 'WITHOUT_TOKEN_ONLY',
}

export enum AuthMetaEnum {
  ROLES = 'ROLES',
  TOKEN_META = 'TOKEN_META',
}
